### ISSUE TITLE
Odd behavior: Incompatibility with Angular 2 rc.6?

### ISSUE THREAD

**Issue by RoxKilly** [systemjs/plugin-text#40]
@guybedford  after following the instructions from your README to inline templates into my application, something odd is happening.

This works with no errors:
```
@Component({
    ...
    template: require('./app.component.html!text'),
})
```

This raises compilation errors (ts compiler believes `htmlTemplate` to be incompatible with type `string`), but it also works in the browser:
```
 import htmlTemplate = require('./app.component.html!text');
@Component({
    ...
    template: htmlTemplate,
})
```

But the syntax we're supposed to use doesn't work:
```
import htmlTemplate from './app.component.html!text';
@Component({
    ...
    template: htmlTemplate,
})
```
ZoneJS `normalizeDirective()` throws error:

> No template specified for component

If I call `console.log(htmlTemplate)` after the import, I get `undefined`. 

I get the same resulting error if I change my import to:
```
import htmlTemplate from './app.component.html';
```
and setup this plugin as the loader in **systemjs.config.js**
```
var packages = {
    'app': {
        main: './main.js',
        defaultExtension: 'js' ,
        meta: {'*.html': {'loader': 'text'}}
    },
}
```

Curiously enough, the html file is downloaded correctly (shows up in network log). Is there any known incompatibility with Angular 2 or am I missing something?

`systemjs-plugin-text 0.0.9`, `Angular 2 rc.6`, `typescript 2.0.2`, `systemjs 0.19.27`

**Comment by fictitious** [comment]
[works for me](https://github.com/fictitious/example-typescript-systemjs-html-import) when I set `"module": "system"` in tsconfig.json. 

So I'd say it's an incompatibility with `CommonJS` typescript output module format (I haven't tried anything else besides `CommonJS` and `system`.)

**Comment by aluanhaddad** [comment]
There are several issues here.
  1. You should configure SystemJS to load HTML files using `package.meta` configuration.
  e.g:

  ```JavaScript
  packages: {
    app: {
      meta: {
        "*.html": {
          loader: "text"
        }
      }
    }
  }
  ```

  This is considered a good practice in SystemJS and is preferable to the explicit plugin syntax.
  2. Starting with TypeScript 2.0, you can declare wildcard ambient modules to fix the type errors. Add this to global .d.ts file.

  ```TypeScript
  declare module "*.html": { export default ""; }
  ```

  3. Now for the difficult part, there's currently a bug which has been mentioned in several issues which is preventing this from working. I think it has to do with metadata between module formats because the text plugin defaults to an anonymous AMD module that simply returns the text of the template. Metadata should map it into the default export and this used to work perfectly but I've recently had trouble with this and it's not TypeScript related. 

@guybedford I believe the corresponding issue was closed in favor of another issue but that issue is not related at all, as it is strictly about TypeScript compile time errors and has no impact on runtime behavior or emitted code.

**Comment by RoxKilly** [comment]
@fictitious 

Artem, sorry it took me a while to respond. the Angular official docs use `"module":"commonjs"` and since I'm new to this I am really careful about taking the less traveled path.  Once I switched to `system`, the app would no longer work.  I [eventually figured out](https://github.com/angular/angular/issues/6053#issuecomment-214163297) that I needed to replace
```
@Component({
    module: moduleId,
    ...
})
 ```
With
```
@Component({
    module: __moduleName,
    ...
})
```

Once I made the switch and could run the app, the import worked as advertised. Thanks a lot.

@guybedford  For what it's worth, I think it would be a good idea to mention in the README that the syntax given there requires `system` modules, with an allusion to the `tsconfig` setting.

**Comment by aluanhaddad** [comment]
@guybedford I can no longer reproduce the bug I was commenting on sorry for any confusion. 
@RoxKilly Regarding documentation, it seems that plugin-typescript only supports `"system"` at this point. It could support others, but the semantics of the register (system) format are much closer to ESModules, making it an excellent option.
