### ISSUE TITLE
Please allow bower installation

### ISSUE THREAD

**Issue by unsafecode** [systemjs/plugin-text#6]
Otherwise is simply out-of-standard

**Comment by guybedford** [comment]
Would npm installation help you?

**Comment by unsafecode** [comment]
Sort of, but we're presently using SystemJS in place of Require, so we are targeting browsers.

The point is actually simple: we have to remember to copy this plugin within System folder, which is problematic because it falls out of the standard setup process (bower install & co.)

**Comment by guybedford** [comment]
The general trend these days is for users to use npm in place of Bower for the same purposes, for better or for worse.

**Comment by unsafecode** [comment]
Could be in the following months, but as of today installing systemjs from npm makes it harder to deploy in web applications, because the folder structure npm uses is definitely non eligible for browsers.

**Comment by guybedford** [comment]
Yes that's my argument too, but the trend is still going ahead with it. npm 3 will be flatter so that this won't be so much of an issue in future.

Personally I would rather have the split of Bower for front-end and npm for Node-style requires as well.

But Bower is looking like it is going out of fashion quickly unfortunately.

**Comment by unsafecode** [comment]
Well, anyway, in this particular case, npm would probably suffice

**Comment by Geen-Henk** [comment]
Just use:

    bower install https://github.com/systemjs/plugin-text.git

**Comment by breandr** [comment]
npm install git+https://github.com/systemjs/plugin-text.git gives the error: "No name provided in package.json". Can we get that added please?

**Comment by kburson** [comment]
+1, although this is a 'slightly' different issue, so I will open a new issue.

**Comment by kburson** [comment]
My observations of the various package managers (I think JSPM is the best) when utilized by web app devs using node as a dev environment only, not a production environment, is that npm is preferred over bower because it is more stable, more supported and has better features for keeping dependencies up to date.

The issue of having the dependency folder being clean and void of any non-browser dependencies seems to be moot in todays environment of transpilers and build tools.  

I may be wrong, and please educate me if you see it another way, but modern websites are becoming increasingly complex, and with the release of ES2015 (ES6) and the promotion of Typescript by both Google and M$, it is becoming necessary to have a transpile process, (same if you prefer coffeescript).

To support this transpile process you will be using either a built task tool (ie grunt | gulp) or a bundler (jspm-builder | webpack | browserify).  In any case the build tool can either copy the desired dependencies from your dependency folder (`node_modules` | 'jspm_components` | 'bower_components') into your distribution folder, or read these dependencies into the bundled file, or both, depending on your process.  

In my perspective this is better since the only files that I am including in my distribution are the specific js/css/img files that I want to use and none of the other cruft that comes along with a bower repo (bower.json, README, build files, demo folders, src folder etc).
